// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApWyxw4ieE5TjoSJ7gDlETFF66E1ScE9M',
    appId: '1:209880408158:web:f9062f20bc8b327d2854cf',
    messagingSenderId: '209880408158',
    projectId: 'fruit-market-21104',
    authDomain: 'fruit-market-21104.firebaseapp.com',
    storageBucket: 'fruit-market-21104.appspot.com',
    measurementId: 'G-K59X18NX8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQXLEF9dSQEOpHNBclG1tXp-yYCja7iqs',
    appId: '1:209880408158:android:9622409254c510962854cf',
    messagingSenderId: '209880408158',
    projectId: 'fruit-market-21104',
    storageBucket: 'fruit-market-21104.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNNG6TcvBfPSWvl-XoFHdfSQKICjlEuG0',
    appId: '1:209880408158:ios:32bd79b1dc98c6cc2854cf',
    messagingSenderId: '209880408158',
    projectId: 'fruit-market-21104',
    storageBucket: 'fruit-market-21104.appspot.com',
    androidClientId: '209880408158-7cuis1o0ucrmt3kc20luf3olgula6sus.apps.googleusercontent.com',
    iosClientId: '209880408158-u0ijmg1te5g9uhhihvth6br96olhiai0.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsMarket',
  );
}
